/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/snuff.glb -t -r public --draco 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CLOTHE_KNOT1: THREE.Mesh
    GLOBE: THREE.Mesh
    NEW_KNOT_MID1: THREE.Mesh
    ROPE: THREE.Mesh
    STRAP: THREE.Mesh
    THREADS2: THREE.Mesh
    TOP_WOOD2: THREE.Mesh
  }
  materials: {
    ['MAT - Snuff Cup']: THREE.MeshStandardMaterial
  }
}

export function Snuff(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/snuff.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CLOTHE_KNOT1.geometry} material={materials['MAT - Snuff Cup']} rotation={[-2.445, 1.38, 1.023]} />
      <mesh geometry={nodes.GLOBE.geometry} material={materials['MAT - Snuff Cup']} rotation={[-2.445, 1.38, 1.023]} />
      <mesh geometry={nodes.NEW_KNOT_MID1.geometry} material={materials['MAT - Snuff Cup']} rotation={[-2.445, 1.38, 1.023]} />
      <mesh geometry={nodes.ROPE.geometry} material={materials['MAT - Snuff Cup']} rotation={[-2.445, 1.38, 1.023]} />
      <mesh geometry={nodes.STRAP.geometry} material={materials['MAT - Snuff Cup']} rotation={[-2.445, 1.38, 1.023]} />
      <mesh geometry={nodes.THREADS2.geometry} material={materials['MAT - Snuff Cup']} rotation={[-2.445, 1.38, 1.023]} />
      <mesh geometry={nodes.TOP_WOOD2.geometry} material={materials['MAT - Snuff Cup']} rotation={[-2.445, 1.38, 1.023]} />
    </group>
  )
}

useGLTF.preload('/models/snuff.glb')
